config/routes.rb
Rails.application.routes.draw do
    
  resources :tweets do
    collection do
      post :confirm
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :content, length: { in:1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shiotter_controller.rb
class ShiotterController < ApplicationController
  def index
  end
    
  def new
    @tweet = Tweet.new
  end
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def index
  end
    
  def new
    @tweet = Tweet.new
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
    
  def new
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end
  end

  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end

  def create
    @tweet = Tweet.new(tweet_params)
    
    if @tweet.save
      #redirect_to tweet_path, notice: "ブログを作成しました"
      redirect_to tweets_path
    else
      render 'new'
    end
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "ツイートを編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path, notice:"ツイートを削除しました！"    
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shiotter_helper.rb
module ShiotterHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shiotter</title>
    <%= csrf_meta_tags %>
    
    <!-- スマホのようなサイズのものにもきちんとデザインが反映されるようになります。 -->
    <meta name="viewport" content="width=device-width">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cont">
      
     <nav class="navbar navbar-default">
       <div class="container-fluid">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
             <span class="sr-only">Shiotter</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=<%= tweets_path %>>Shiotter</a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href=<%= tweets_path %>><span class="glyphicon glyphicon-home">ホーム</a></li>
              <li><a href=""><span class="glyphicon glyphicon-star-empty">モーメント</span></a></li>
              <li><a href=""><span class="glyphicon glyphicon-bell">通知</span></a></li>
              <li><a href="#"><span class="glyphicon glyphicon-envelope">メッセージ</span></a></li>
              <li><a href=<%= new_tweet_path %>><span class="glyphicon glyphicon-book">ツイート</span></a></li>
            </ul>
          </div>
        </div>
      </nav>
  
      <%= yield %>

      <footer class="footer">
        <p>© 2015-2016 Copyright Shiotter</p>
      </footer>
    </div>
  </body>
  
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, url: choose_new_or_edit, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ツイート %>
    <%= form.text_area :content %>
  </div>
  
  <%= form.submit %>

<% end %>

app/views/tweets/confirm.html.erb
<h3>以下の内容でツイートします</h3>

<%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  
  <p>内容：<%= @tweet.content %></p>
  
  <%= form.submit "ツイート" %>

<% end %>

<br>
<br>

<%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "ツイート画面へ戻る", name: 'back' %>
<% end %>
  

app/views/tweets/edit.html.erb
<h2>ツイートを編集する</h2>

<%= render 'form' %>

app/views/tweets/index.html.erb
  
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="my_profile">
          <h3>ユーザ名</h3>
          <p>@user_id</p>
          <p><span class="glyphicon glyphicon-list-alt">2017年8月に登録</span></p>
        </div>
        <div class="recommended">
          <h4>おすすめトレンド</h4>
          <h6>#いい肉の日</h6>
          <h6>重大バグ</h6>
        </div>
     </div>
     
      <div class="col-md-8">
        <% @tweets.each do |tweet| %>
          <div  class="tweet_area">
            <tr>
              <td><%= tweet.content %></td>
              <br>
              <td><%= link_to 'edit', edit_tweet_path(tweet.id) %></td>
              <td><%= link_to 'delete', tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
            <!--
            <td><%#= link_to '詳細を確認する', blog_path(blog.id) %></td>
            <td><%#= link_to 'ブログを編集する', edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' } %></td>
            -->
            </tr>
          </div>  
        <% end %>
    </div>
  </div>
</div>

  

app/views/tweets/new.html.erb
<h2>ツイートする</h2>

<%= render 'form' %>